/***************************************************************************************************
 * MIT License
 *
 * Copyright (c) 2021 antmuse@live.cn/antmuse@qq.com
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
***************************************************************************************************/


#ifndef APP_CERTS_H
#define APP_CERTS_H

#include "Config.h"

namespace app {

static const s8* G_SERVER_CERT =
"-----BEGIN CERTIFICATE-----\n"
"MIID6TCCAtGgAwIBAgIUOYN33CVReC3jXeWkRn0JVEOwu/MwDQYJKoZIhvcNAQEL\n"
"BQAwgYUxCzAJBgNVBAYTAkNOMQswCQYDVQQIDAJCSjELMAkGA1UEBwwCQkoxEzAR\n"
"BgNVBAoMCndpdGNvcmUuY24xEzARBgNVBAsMCndpdGNvcmUuY24xEzARBgNVBAMM\n"
"CndpdGNvcmUuY24xHTAbBgkqhkiG9w0BCQEWDmFudEB3aXRjb3JlLmNuMCAXDTIw\n"
"MDgyNjA5NTkyMloYDzIxMjAwODAyMDk1OTIyWjCBgTELMAkGA1UEBhMCQ04xCzAJ\n"
"BgNVBAgMAkJKMQswCQYDVQQHDAJCSjESMBAGA1UECgwJbG9jYWxob3N0MRIwEAYD\n"
"VQQLDAlsb2NhbGhvc3QxEjAQBgNVBAMMCWxvY2FsaG9zdDEcMBoGCSqGSIb3DQEJ\n"
"ARYNYW50QGxvY2FsaG9zdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB\n"
"AK8MVXGgTnWdJYUF7N3xFb2FTe9yfylluH6fCa5fBC6DlkaVr8+w5h5lyl7arRMf\n"
"ctm1n/N04iBUZsa2wBwr/xWN7V0SjHh0Mnuvxfeeqgjgy63FSE73odz0lD/pBtw2\n"
"wVlX6yDJo9gDcDiklkNGyFOo987iI+kuVOvR+DFRCHyWZbGGdjEdQjuiylWZchXR\n"
"/rM9BPa7ovlY7djWFd80HgIWVkHNuKwzidzkxolJg97RqnFicittIS96GGgxUIUN\n"
"NVzBwamTrtj+unRJ/zheGVzp5pG0+fvQpER9xeY4P0csq7vaNQ6tiohie7kRu0GL\n"
"QtYhL9DVBomcNJJ8+ttWhskCAwEAAaNRME8wHwYDVR0jBBgwFoAUyhrRKM3NvPRI\n"
"6CEPk4HSsxEEdaAwCQYDVR0TBAIwADALBgNVHQ8EBAMCBPAwFAYDVR0RBA0wC4IJ\n"
"bG9jYWxob3N0MA0GCSqGSIb3DQEBCwUAA4IBAQB21MTaceN1ADJUykidLJq2CiUZ\n"
"iKek4JwqEH46wOVmhspWSSYlMFzg5CRp4wqebGM4PyBHi1PEFdF2pMoh336UXHc/\n"
"j1OApfaRr8nlo/ImlIhf41Pa9hp9Cx2UVzcxSUioX8t7pMuXT9wEAuWc/9cauRHp\n"
"hSHEpQfqaTO2EGJkzjAI3XiFnXkNa56M88nKLpEiTuL7aJRml9qBbr/N5TxWD1ak\n"
"sKNL5A839P3wM/aEC8eAU5b7nsQZkVhcgCJCIgPEWiEt0/E0WYHNljwKRNg0HhcM\n"
"iGexKdf+XyO7cKAa+plsCBaLiXZnWA5nCjpGYXSoFc0eD8SOjF+ZMvrajiik\n"
"-----END CERTIFICATE-----\n";




static const s8* G_SERVER_KEY =
"-----BEGIN RSA PRIVATE KEY-----\n"
"MIIEpQIBAAKCAQEArwxVcaBOdZ0lhQXs3fEVvYVN73J/KWW4fp8Jrl8ELoOWRpWv\n"
"z7DmHmXKXtqtEx9y2bWf83TiIFRmxrbAHCv/FY3tXRKMeHQye6/F956qCODLrcVI\n"
"Tveh3PSUP+kG3DbBWVfrIMmj2ANwOKSWQ0bIU6j3zuIj6S5U69H4MVEIfJZlsYZ2\n"
"MR1CO6LKVZlyFdH+sz0E9rui+Vjt2NYV3zQeAhZWQc24rDOJ3OTGiUmD3tGqcWJy\n"
"K20hL3oYaDFQhQ01XMHBqZOu2P66dEn/OF4ZXOnmkbT5+9CkRH3F5jg/Ryyru9o1\n"
"Dq2KiGJ7uRG7QYtC1iEv0NUGiZw0knz621aGyQIDAQABAoIBAQCLX+GkUARIhy/5\n"
"g2c+q5coyDvufBadin1kbBKUQNkeg+0iFErgrjP7XgbMkYaepDqY95D8kkL9hNY0\n"
"QAwkIi+/JLsqkPtBaRtM+f5BE5bE7N+fY2YYYfkB6cckP9ETg5FdJrBy8bm/47T1\n"
"lK6DsJcObYmpssru/dHl1c+szJ1aPD8hSBD32o5k1TAD+k8SJeLDiILRokglnAvE\n"
"95sKSMR25JEGniUxJE60zwdWLka8h0Ez8qqySBrDui7+tBqT0nNZns61IXFdsQux\n"
"7VUPye/mUBY6jVPOEahblpjfwVsvGWB5AlidBIj1OvJhfeiDq3NTwWQbmB8SctLu\n"
"4j16xxkBAoGBAOcsnHJOH5Ik1olI3UiV0pDrmMFQlKI8msOf0OZHme3I9iaMstET\n"
"N7eUcOotel+8VBoGn5NIuStlHwJJ1/dVyDcBVSr2adR+yjr2CZnuYF1FmLi0PAiJ\n"
"YOzuzv9NVrHUaP2vw4xWUn4XYK8AZ9J/WIbw3g57v12u7BomY7RG/HGpAoGBAMHY\n"
"t6soO0+XTYNjS32ccqgPosfqAbppCSQ3vOpjgaUXNJsD9psqZSOnQyh/rIUZDmkC\n"
"1AdXN2+QJ/tho6S6RCObqFyc9UwkN6kWHJs/4UCEfEkYXwNgYovdx8E+Nk8Tei9o\n"
"ID9LFqd3oC1WhIuKr9yMg5nCkNdQ8VEZ35HNmOAhAoGBAJkKBX/+jBP54zT7UdMN\n"
"rFpYPcYsjFli+ansESWB3Tt3wM0AdBjJOieEU8QT22GpkZuxKs8cY8mApiijrh+F\n"
"YIhZj4JjougUD9k8rFqFXrIgstwEJYIZQFtaNRr6nhwX3HGlfDVZqD7lRxJTmGfX\n"
"+klLCBZagfOJK7CcHYFpRRIRAoGBAKoD8dNkTeDYy1tZU3SwKr/MNvEwBKQCS8pA\n"
"OKk67RJm7/Sl3TzqShqjMPvsPtvdxg3ENULa8/wda3PHh0eLNwgkFd5kq6BEg60B\n"
"f8WKmX2EtZ1Gis7jUotp0TFj5y4j3x6FLQNWUGBBQ3OAVnAtC2FcvG+3fmHa1ExV\n"
"bQjsUhEBAoGAciZ2M9fK4s1rfH9jfzcD8kj1fEgbaiRVyYFYXV1Wh7UrLcCeCl8A\n"
"mhW3E1gOJBOpADt6Jjn9uOaCXcbPb7iLa1pcO5CWg3D7eUNyAb+tio7e0hqqHRIH\n"
"567gpYOQqIGJ4T8Sbysfia/0K+wuyZttIvIlZqKzQtRGmRIjduVMFao=\n"
"-----END RSA PRIVATE KEY-----\n";



// DigiCert Global Root CA cert, 浏览器中导出的证书
static const s8* G_CA_CERT =
"-----BEGIN CERTIFICATE-----\n"
"MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh\n"
"MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\n"
"d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD\n"
"QTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT\n"
"MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j\n"
"b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG\n"
"9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB\n"
"CSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97\n"
"nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt\n"
"43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P\n"
"T19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4\n"
"gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO\n"
"BgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR\n"
"TLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw\n"
"DQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr\n"
"hMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg\n"
"06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF\n"
"PnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls\n"
"YSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk\n"
"CAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=\n"
"-----END CERTIFICATE-----\n";


//GlobalSign Root CA, 浏览器中导出的证书
static const s8* G_CA_CERT1 =
"-----BEGIN CERTIFICATE-----\n"
"MIIDdTCCAl2gAwIBAgILBAAAAAABFUtaw5QwDQYJKoZIhvcNAQEFBQAwVzELMAkG\n"
"A1UEBhMCQkUxGTAXBgNVBAoTEEdsb2JhbFNpZ24gbnYtc2ExEDAOBgNVBAsTB1Jv\n"
"b3QgQ0ExGzAZBgNVBAMTEkdsb2JhbFNpZ24gUm9vdCBDQTAeFw05ODA5MDExMjAw\n"
"MDBaFw0yODAxMjgxMjAwMDBaMFcxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9i\n"
"YWxTaWduIG52LXNhMRAwDgYDVQQLEwdSb290IENBMRswGQYDVQQDExJHbG9iYWxT\n"
"aWduIFJvb3QgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDaDuaZ\n"
"jc6j40+Kfvvxi4Mla+pIH/EqsLmVEQS98GPR4mdmzxzdzxtIK+6NiY6arymAZavp\n"
"xy0Sy6scTHAHoT0KMM0VjU/43dSMUBUc71DuxC73/OlS8pF94G3VNTCOXkNz8kHp\n"
"1Wrjsok6Vjk4bwY8iGlbKk3Fp1S4bInMm/k8yuX9ifUSPJJ4ltbcdG6TRGHRjcdG\n"
"snUOhugZitVtbNV4FpWi6cgKOOvyJBNPc1STE4U6G7weNLWLBYy5d4ux2x8gkasJ\n"
"U26Qzns3dLlwR5EiUWMWea6xrkEmCMgZK9FGqkjWZCrXgzT/LCrBbBlDSgeF59N8\n"
"9iFo7+ryUp9/k5DPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8E\n"
"BTADAQH/MB0GA1UdDgQWBBRge2YaRQ2XyolQL30EzTSo//z9SzANBgkqhkiG9w0B\n"
"AQUFAAOCAQEA1nPnfE920I2/7LqivjTFKDK1fPxsnCwrvQmeU79rXqoRSLblCKOz\n"
"yj1hTdNGCbM+w6DjY1Ub8rrvrTnhQ7k4o+YviiY776BQVvnGCv04zcQLcFGUl5gE\n"
"38NflNUVyRRBnMRddWQVDf9VMOyGj/8N7yy5Y0b2qvzfvGn9LhJIZJrglfCm7ymP\n"
"AbEVtQwdpf5pLGkkeB6zpxxxYu7KyJesF12KwvhHhm4qxFYxldBniYUr+WymXUad\n"
"DKqC5JlR3XC321Y9YeRq4VzW9v493kHMB65jUr9TU/Qr6cf9tveCX4XSQRjbgbME\n"
"HMUfpIBvFSDJ3gyICh3WZlXi/EjJKSZp4A==\n"
"-----END CERTIFICATE-----\n";



//trusted Root CA cert, 自用测试
static const s8* G_CA_ROOT_CERT =
"-----BEGIN CERTIFICATE-----\n"
"MIID7zCCAtegAwIBAgIUPI6E5oROadR04LQU7h9iiVr7/w0wDQYJKoZIhvcNAQEL\n"
"BQAwgYUxCzAJBgNVBAYTAkNOMQswCQYDVQQIDAJCSjELMAkGA1UEBwwCQkoxEzAR\n"
"BgNVBAoMCndpdGNvcmUuY24xEzARBgNVBAsMCndpdGNvcmUuY24xEzARBgNVBAMM\n"
"CndpdGNvcmUuY24xHTAbBgkqhkiG9w0BCQEWDmFudEB3aXRjb3JlLmNuMCAXDTIw\n"
"MDgyNjA5NTYzNFoYDzMwMTkxMjI4MDk1NjM0WjCBhTELMAkGA1UEBhMCQ04xCzAJ\n"
"BgNVBAgMAkJKMQswCQYDVQQHDAJCSjETMBEGA1UECgwKd2l0Y29yZS5jbjETMBEG\n"
"A1UECwwKd2l0Y29yZS5jbjETMBEGA1UEAwwKd2l0Y29yZS5jbjEdMBsGCSqGSIb3\n"
"DQEJARYOYW50QHdpdGNvcmUuY24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK\n"
"AoIBAQDIXcEuypqGg8NgnpsfnjENcwDBh6S/GO5G30TNg+l3AiqtuA5xytYPk6qS\n"
"SicvhWyVay4wptDp7j9Sup5OSvaQ/uklLb7wYsK9gQsEBhyTSO3Dk6Y7eGBr6HgU\n"
"arA6o+e4YtrFVmX492gBHwzPzAua4eTYyM+O5KkW/YOB5ahhG8Nt4r8tkVValzYO\n"
"OrRPZDupbOE3IatPh2pgncW6kY5WDm2rxX9250kcBBg2xj/eNgfMQNiU0DMX0b66\n"
"Guznx//JM7Z7AlyHI2wehCnHKWCUjY6Om9+Mk+QmegtarQ5+ERSsBWP5zkYtOPAv\n"
"kuFri5FT7Nh+njjEaSQsqF3DdYYfAgMBAAGjUzBRMB0GA1UdDgQWBBTKGtEozc28\n"
"9EjoIQ+TgdKzEQR1oDAfBgNVHSMEGDAWgBTKGtEozc289EjoIQ+TgdKzEQR1oDAP\n"
"BgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQACcfwARPgwvgQ650di\n"
"BqT/YbRBM9OdCanDt8lSSxyTnan1+/abdHJ3W6w6wTL9AW9hU9qrYMVNNSQUe2GZ\n"
"G8jA++/fxszm+RT6kP1hln0nRzOk27rFTYR4SC7tB8B2aIZ7b4dlatBEuiVJEm5A\n"
"/+bZsOyh6Rp9li2UbuFthATSfXRo+I3jndRA0BBVvZOzFpT5DZwGjHQpvWO8lUy4\n"
"WAjVrvlnax/ifGS8XmIpKP5eROlI2TcPH5KR8/C4qyCUdLG4N9hHXld1etiMporb\n"
"ykRj5tFB58RMa2Xpnz515434HTt/DB9B+n8V0m6hwXvhD7do049SNcF7MR91GtZw\n"
"doIB\n"
"-----END CERTIFICATE-----\n";


}//namespace app

#endif //APP_CERTS_H